// Content block types for blog posts
export interface ContentBlockBase {
  id: string;
  type: string;
  order: number;
}

export interface TitleBlock extends ContentBlockBase {
  type: 'title';
  content: string;
}

export interface HeadlineBlock extends ContentBlockBase {
  type: 'headline';
  content: string;
  level: 1 | 2 | 3 | 4 | 5 | 6;
}

export interface ExcerptBlock extends ContentBlockBase {
  type: 'excerpt';
  content: string;
}

export interface DividerBlock extends ContentBlockBase {
  type: 'divider';
  style?: 'solid' | 'dashed' | 'dotted';
}

export interface TextBlock extends ContentBlockBase {
  type: 'text';
  content: string;
}

export interface ImageBlock extends ContentBlockBase {
  type: 'image';
  url: string;
  alt?: string;
  caption?: string;
}

export interface ProductBlock extends ContentBlockBase {
  type: 'product';
  productId: string;
  productName?: string;
  description?: string;
  imageUrl?: string;
}

export interface SnippetBlock extends ContentBlockBase {
  type: 'snippet';
  content: string;
  language?: string;
}

export type ContentBlock =
  | TitleBlock
  | HeadlineBlock
  | ExcerptBlock
  | DividerBlock
  | TextBlock
  | ImageBlock
  | ProductBlock
  | SnippetBlock;

export interface Product {
  id: string;
  name: string;
  description: string;
  price: string;
  url: string;
  imageUrl: string;
  category: string;
  tags: string[];
  inStock: boolean;
  searchUrl?: string;
}

export interface AmazonProduct {
  title: string;
  query: string;
  searchUrl: string;
  affiliateUrl: string;
  imageUrl: string;
  price: string;
  category: string;
  asin: string;
}

// Blog related types
export interface BlogPost {
  id: string;
  slug: string;
  publishedDate: string;
  author: {
    name: string;
    avatar?: string;
    bio?: string;
  };
  tags: string[];
  readingTime: string;
  coverImage?: string;

  // The title, excerpt, and all content are now represented as blocks
  contentBlocks: ContentBlock[];

  // Legacy fields for backward compatibility
  title: string;
  excerpt: string;
  content: string;
  images?: string[];
  featuredProductId?: string;
  recommendedProductIds?: string[];
  recommendations?: Product[];
  amazonProducts?: AmazonProduct[];
  autoGenerated?: boolean;
  sourceUrl?: string;
}

// Window interface for Twitter
declare global {
  interface Window {
    twttr?: {
      widgets: {
        load(): void;
      };
    };
  }
}